$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  default_container:
    type: string
  reference:
    fasta: string
    required:
      - fasta
  bwa_mem:
    type: object
    properties:
      benchmark_repeats:
        type: string
        description: set number of times benchmark should be repeated for bwa_mem
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to bwa_mem
      sort:
        type: string
        description: program hangling the bam sorting (default: samtools)
      sort_order:
        type: string
        description: how the bam file should be sorted (default: coordinate)
      sort_extra:
        type: string
        description: parameters that should be forwarded to sorting (ie, number of threads)
    required:
      - extra
  required:
    - samples
    - units
    - default_container
    - bwa_mem
    - reference
