$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  alignment_software:
    type: string
  samples:
    type: string
  units:
    type: string
  default_container:
    type: string
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: fasta reference file
      skip_chrs:
        type: array
        items:
            type: string
        description: list of chromosomes that should be skipped
    required:
      - fasta

  bwa_mem:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for bwa_mem
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to bwa_mem
      sorting:
        type: string
        description: program hangling the bam sorting (default samtools)
      sort_order:
        type: string
        description: how the bam file should be sorted (default coordinate)
      sort_extra:
        type: string
        description: parameters that should be forwarded to sorting (ie, number of threads)
    required:
      - extra

  extract_reads:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for extract_reads
      container:
        type: string
        description: name or path to docker/singularity container

  mark_duplicates:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for mark_duplicates
      container:
        type: string
        description: name or path to docker/singularity container

  samtools_index:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for samtools_index
      container:
        type: string
        description: name or path to docker/singularity container

  merge_bam:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for merge_bam
      container:
        type: string
        description: name or path to docker/singularity container

  required:
    - samples
    - units
    - default_container
    - bwa_mem
    - reference
