$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file for dna references
type: object
properties:
  reference:
    type: object
    description: reference used by alignment
    properties:
      star_index:
        type: string
        description: path to star reference index
    required:
      - star_index

required:
  - reference
