samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

default_container: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"
  extra: "-R '@RG\\tID:{sample}\\tSM:{sample}\\tPL:illumina\\tPU:{sample}' -v 1 "

mark_duplicates:
  container: "docker://gmsuppsala/somatic:develop"

samtools_index:
  container: "docker://gmsuppsala/somatic:develop"

merge_bam:
  container: "docker://gmsuppsala/somatic:develop"
