samples: "samples.tsv"
units: "units.tsv"
resources: "resources.yaml"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/WASH7P.fna"
  dict: "reference/WASH7P.dict"
  amb: "reference/WASH7P.fna.amb"
  ann: "reference/WASH7P.fna.ann"
  bwt: "reference/WASH7P.fna.bwt"
  fai: "reference/WASH7P.fna.fai"
  pac: "reference/WASH7P.fna.pac"
  sa: "reference/WASH7P.fna.sa"

bwa_mem:
  container: "docker://hydragenetics/bwa_mem:0.7.17"

mark_duplicates:
  container: "docker://hydragenetics/picard:2.25.0"

samtools_index:
  container: "docker://hydragenetics/common:0.0.1"

merge_bam:
  container: "docker://hydragenetics/common:0.0.1"
