samples: "samples.tsv"
units: "units.tsv"

tools:
  common: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"

bwa_mem:
  container: "docker://gmsuppsala/somatic:develop"
  threads: 2
  params:
    extra: r"-R '@RG\tID:{sample}\tSM:{sample}\tPL:illumina\tPU:{sample} -v 1 '"
